### ISSUE TITLE
Implement dynamic authentication screen

### ISSUE THREAD

**Issue by elenaustyugova** [o360/frontend#11]
**Description**
Dynamically draw an authentication form, including elements for authentication through social networks and / or through login and password using the endpoint from [#11](https://github.com/o360/backend/issues/11)

**Todos:**
- [x] Create and approve with PO mockups
- [x] Implement the use cases
- [x] Rework configuring
- [x] Document deployment and configuring 

**Use cases**
https://docs.google.com/document/d/1tnX6a-4Qhrd5OJpIqVOCn6Bj5WzvydSddTLR2T2dPHI/edit

**Mockups**
<img width="513" alt="Screen Shot 2020-02-21 at 9 56 56 AM" src="https://user-images.githubusercontent.com/9375213/75000928-7b5ef300-5492-11ea-9408-58aaffa21a2a.png">
<img width="502" alt="Screen Shot 2020-02-21 at 10 00 20 AM" src="https://user-images.githubusercontent.com/9375213/75000934-844fc480-5492-11ea-8ddf-7ad95e1e0b7f.png">

**Req ID:** REQF_login-003

**Comment by vanekbr** [comment]
@bwsw Please, take a look at mockups and either approve or leave comments.
